### ISSUE TITLE
package build attempts to make changes to build user's homedir

### ISSUE THREAD

**Issue by jamincollins** [frealgagu/archlinux.flutter#11]
The issue appears to be caused by this line from the `PKGBUILD`:
```
  "${srcdir}/${pkgname}/bin/${pkgname}" doctor
```
https://github.com/frealgagu/archlinux.flutter/blob/master/PKGBUILD#L30

# Reproduction

Dockerfile:
```
FROM archlinux:base-devel as base

RUN pacman --sync --refresh --sysupgrade --noconfirm --noprogressbar --quiet
RUN pacman --sync --noconfirm --noprogressbar --quiet git namcap
RUN yes | pacman --sync --clean --clean

# specifically not creating a homedir here to illustrate the problem
RUN useradd --comment "Arch Build User" build

RUN mkdir /package

FROM scratch as syncdeps

ENV LANG en_US.UTF-8

WORKDIR /package

COPY --from=base / /

RUN usermod -aG wheel build
RUN echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER build

CMD ["makepkg", "--force", "--syncdeps", "--noconfirm"]
```

Build and tag the image:
```
docker build . -t minimal-arch-build
```

Attempt to build the flutter AUR package:
```
docker run --rm -v $(pwd):/package minimal-arch-build
```

Failure output:
```
==> Extracting sources...
  -> Extracting flutter-2.5.3.tar.xz with bsdtar
==> Starting build()...
Unhandled exception:
Exception: Flutter failed to create a directory at "/home/build/.config/flutter".
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:813:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:607:7)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#5      new Config._common (package:flutter_tools/src/base/config.dart:77:17)
#6      new Config (package:flutter_tools/src/base/config.dart:37:19)
#7      new _DefaultPersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:69:18)
#8      new PersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:21:9)
#9      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:302:34)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#14     PersistentToolState.instance (package:flutter_tools/src/persistent_tool_state.dart:35:55)
#15     persistentToolState (package:flutter_tools/src/globals_null_migrated.dart:63:69)
#16     _defaultBotDetector (package:flutter_tools/src/globals_null_migrated.dart:69:24)
#17     _defaultBotDetector (package:flutter_tools/src/globals_null_migrated.dart)
#18     botDetector (package:flutter_tools/src/globals_null_migrated.dart:65:62)
#19     isRunningOnBot (package:flutter_tools/src/globals_null_migrated.dart:75:36)
#20     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:81:34)
#21     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:80:28)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
#24     _rootRun (dart:async/zone.dart:1428:13)
#25     _CustomZone.run (dart:async/zone.dart:1328:19)
#26     _runZoned (dart:async/zone.dart:1863:10)
#27     runZoned (dart:async/zone.dart:1785:10)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
#29     runInContext (package:flutter_tools/src/context_runner.dart:85:18)
#30     run (package:flutter_tools/runner.dart:45:10)
#31     main (package:flutter_tools/executable.dart:92:9)
#32     main (file:///b/s/w/ir/x/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:10:3)
#33     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by jamincollins** [comment]
In addition to the above report, the listed dependencies are only _runtime_ dependencies.  As such, they are not needed for build.

The following diff resolves both issues.

```
diff --git a/PKGBUILD b/PKGBUILD
index ae1100440cae63528ded411d11eb8e04c6e67e00..d385e18158b4acafdb0d02bca16c0bf676cd359d 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -8,9 +8,7 @@ pkgdesc="A new mobile app SDK to help developers and designers build modern mobi
 arch=("x86_64")
 url="https://${pkgname}.dev"
 license=("custom" "BSD" "CCPL")
-depends=("git" "glu" "java-environment" "libglvnd" "unzip")
 optdepends=("android-sdk" "android-studio" "intellij-idea-community-edition" "intellij-idea-ultimate-edition" "perl" "python")
-makedepends=("python")
 backup=("opt/${pkgname}/packages/${pkgname}_test/pubspec.yaml" "opt/${pkgname}/packages/${pkgname}/pubspec.yaml")
 options=("!emptydirs")
 install="${pkgname}.install"
@@ -25,12 +23,8 @@ sha256sums=(
   "7ef10d753cfaac52d243549764a793f44f8284a1f4b11715ccd2fa915b026a6f"
 )
 
-build() {
-  cd "${srcdir}/${pkgname}"
-  "${srcdir}/${pkgname}/bin/${pkgname}" doctor
-}
-
 package() {
+  depends=("git" "glu" "java-environment" "libglvnd" "unzip")
   rm -rf "${srcdir}/${pkgname}/bin/cache" "${srcdir}/${pkgname}/.pub-cache"
   install -Dm644 "${srcdir}/${pkgname}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
   install -Dm755 "${srcdir}/${pkgname}.sh" "${pkgdir}/etc/profile.d/${pkgname}.sh"
```

**Comment by jamincollins** [comment]
It's been a few months, any update?

**Comment by frealgagu** [comment]
It's strange that you use depends only in package step (finally you need it already installed for the package to install it).
I have never run it in a docker, I always compile it in a clean chroot environment: 
https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot
and the generated package is uploaded as releases here in github.

**Comment by jamincollins** [comment]
I believe you're missing the point.  A package build should alter a user's home directory.  It's not a question of permissions, but the actions that are being taken.  User specific actions should be taken at runtime.  The changes I propose follow this model and AFAICT don't break anything.

**Comment by frealgagu** [comment]
Yes, you're right, I had misunderstood your message. A build shouldn't change any directory. Maybe we could add flutter doctor to install file, or at least instructions about what to do. I think running doctor is important to help us configuring the tools and check if something is missing.
